include:
  - ./docker/elastic.yml
  - ./docker/magento.yml
  - ./docker/postgres.yml
  # - ./docker/redis.yml
  - ./webshop-api/docker-compose.yml
  - ./search-api/docker-compose.yml
  - ./order-mngt-api/docker-compose.yaml
  # - ./payments/docker-compose.yml

networks:
  default:
    name: webshop
    driver: bridge
